config/routes.rb
Rails.application.routes.draw do
  
  get 'likes/create'
  get 'likes/destroy'
  root 'pages#index'
  get 'user/:id', to: 'pages#dashboard', as: 'user'
  get '/search', to: 'pages#search', as: 'search'
  post '/user/:id/follow', to: "follows#follow", as: "follow_user"
  post '/user/:id/unfollow', to: "follows#unfollow", as: "unfollow_user"
  get '/user/:id/followers', to: "follows#followers", as: "user_followers"
  devise_for :users
  delete 'tweeets/:tweeet_id/comment/:id', to: 'comments#destroy', as: "destroy_comment"
  put 'tweeets/:id/like', to: 'likes#create', as: "like"
  delete 'tweeets/:id/unlike', to: 'likes#destroy', as: "unlike"
  resources :tweeets do
    resources :comments
  end 
  resources :conversations do
    resources :messages
    delete '/read', to: "messages#read"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :conversation
    belongs_to :user
    has_many :notifications, dependent: :destroy
    validates_presence_of :body, :conversation_id, :user_id

    def message_time
        created_at.strftime("%l:%M %p")
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_conversation

  def index
  @messages = @conversation.messages
    if @messages.length > 15
        @over_fifteen = true
        @messages = @messages.last(15) # @messages[-10..-1]
    end
    if params[:m]
        @over_fifteen = false
        @messages = @conversation.messages
    end
  @message = @conversation.messages.build
  end


  def new
    @message = @conversation.messages.build
  end

  def create
    @message = @conversation.messages.build(message_params)

    if @conversation.sender_id == current_user.id 
      recipient = User.find(@conversation.recipient_id)
    else
      recipient = User.find(@conversation.sender_id)
    end
    
    @notification = Notification.create(recipient: recipient.id,actor: current_user.id, message:@message, conversation:@conversation)
    @notification.save
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to conversation_messages_path(@conversation)
  end

  def read
    notify = Notification.where(conversation_id: params[:conversation_id])
    notify.destroy_all
    redirect_to conversation_messages_path(@conversation)
  end

  private
    def find_conversation
      @conversation = Conversation.find(params[:conversation_id])
    end
    
    def message_params
      params.require(:message).permit(:body, :user_id)
    end

end

app/helpers/messages_helper.rb
module MessagesHelper

  
  def message_date message
    return "Today" if message.created_at.to_date ==  Date.today
    return "Yesterday" if message.created_at.to_date ==Date.yesterday
    return  message.created_at.strftime("%d/%m/%Y") rescue nil
  end

end

app/views/messages/index.html.erb
<div class="d-flex justify-content-between mt-1 mb-4 px-3">
  <%= link_to  conversation_messages_path(@conversation) do %>
    <%= fa_icon "refresh" , class: "btn btn-warning"%>
  <% end %>
  <%= link_to conversations_path do %>
    <%= fa_icon "backward" , class: "btn btn-info"%>
  <% end %>
</div>
<div class="row rounded-lg overflow-hidden shadow m-1">
  <div class="col-12 px-0">
    <div class="bg-light">
      <div class="bg-primary px-4 py-2">
         <% if @conversation.sender_id == current_user.id %>
            <% recipient = User.find(@conversation.recipient_id)%>
          <% else %>
            <% recipient = User.find(@conversation.sender_id)%>
          <% end %>
          <%= link_to user_path(recipient) do %>
            <p class="h5 mb-0 py-1 text-white"><%= recipient.fullname%></p>
          <% end %>
      </div>
      <!-- Chat Box-->
      <div class="px-0">
        <div class="px-4 py-5 chat-box bg-white">
          <div class="message-scroll" id="messages">
            <% if @over_fifteen %>
              <div class="text-center mb-3">
                <%= link_to "Show privious", '?m=all', class: "badge badge-primary" %>
              </div>
            <% end %>
            <% @date = []%>
            <% @messages.each do |message| %>
              <% if !message.created_at.nil? %>
                <% unless @date.include? message.created_at.to_date %>
                  <% @date << message.created_at.to_date  %>
                  <div class="main-divider mb-3"><h6 class="inner-divider"><span><%= message_date(message) %></span></h6></div>
                <% end %>
              <% end %>
              <% if message.body.present?%>
                <% if message.user_id == current_user.id %>
                    <!-- Reciever Message-->
                    <div class="media w-50 ml-auto mb-3">
                      <div class="media-body">
                        <div class="bg-primary rounded py-2 px-3 mb-2">
                        <p class="text-small mb-0 text-white"><%= message.body%></p>
                        </div>
                        <p class="small text-muted"><%= message.message_time%>
                        <%= link_to "Delete", conversation_message_path(@conversation,message), method: :delete, class: "float-right text-danger", data: { confirm: "Are you sure"} %></p>
                      </div>
                    </div>
                <% else %>
                <!-- Sender Message-->
                    <div class="media w-50 mb-3">
                      <div class="media-body ml-3">
                        <div class="bg-light rounded py-2 px-3 mb-2 border">
                        <p class="text-small mb-0 text-dark"><%= message.body%></p>
                        </div>
                        <p class="small text-muted"><%= message.message_time%></p>
                      </div>
                    </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <!-- Typing area -->
          <div class="bg-light" id="input-bar">
            <%= form_for([@conversation,@message]) do |f| %>
              <div class="input-group border">
                <%= f.text_field :body, class: "form-control rounded-0 border-0 py-4 bg-light" ,placeholder:"Type a message", autofocus: true%>
                <%= f.text_field :user_id, value: current_user.id, type: "hidden"%>
                <div class="input-group-append">
                  <%= f.submit "send", class: "btn btn-primary"%>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
var messages = document.getElementById("messages");
    messages.scrollTop = messages.scrollHeight;
</script>