config/routes.rb
Rails.application.routes.draw do
  
  get 'likes/create'
  get 'likes/destroy'
  root 'pages#index'
  get 'user/:id', to: 'pages#dashboard', as: 'user'
  get '/search', to: 'pages#search', as: 'search'
  post '/user/:id/follow', to: "follows#follow", as: "follow_user"
  post '/user/:id/unfollow', to: "follows#unfollow", as: "unfollow_user"
  get '/user/:id/followers', to: "follows#followers", as: "user_followers"
  devise_for :users
  delete 'tweeets/:tweeet_id/comment/:id', to: 'comments#destroy', as: "destroy_comment"
  put 'tweeets/:id/like', to: 'likes#create', as: "like"
  delete 'tweeets/:id/unlike', to: 'likes#destroy', as: "unlike"
  resources :tweeets do
    resources :comments
  end 
  resources :conversations do
    resources :messages
    delete '/read', to: "messages#read"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweeet.rb
class Tweeet < ApplicationRecord
    belongs_to :user
    has_one_attached :tweeet_image
    has_rich_text :tweeet
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    
    def liked?(user)
        !!self.likes.find{|like| like.user.id == user.id}
    end
end

app/controllers/tweeets_controller.rb
class TweeetsController < ApplicationController
  before_action :set_tweeet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show]

  # GET /tweeets or /tweeets.json
  def index
      @tweeets = current_user.tweeets.all.order(created_at: :desc)
      @tweeet = Tweeet.new
    @user = User.order(created_at: :desc).last(10)
  end

  # GET /tweeets/1 or /tweeets/1.json
  def show
    @comment = @tweeet.comments.build
  end

  # GET /tweeets/new
  def new
    @tweeet = current_user.tweeets.build
  end

  # GET /tweeets/1/edit
  def edit
  end

  # POST /tweeets or /tweeets.json
  def create
    @tweeet = current_user.tweeets.build(tweeet_params)

    respond_to do |format|
      if @tweeet.save
        format.html { redirect_to tweeets_url }
        format.json { render :show, status: :created, location: @tweeet }
      else
        format.html { redirect_to tweeets_url  status: :unprocessable_entity }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeets/1 or /tweeets/1.json
  def update
    respond_to do |format|
      if @tweeet.update(tweeet_params)
        format.html { redirect_to tweeets_url notice: "Tweeet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweeet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeets/1 or /tweeets/1.json
  def destroy
    @tweeet.destroy
    respond_to do |format|
      format.html { redirect_to tweeets_url, notice: "Tweeet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeet
      @tweeet = Tweeet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweeet_params
      params.require(:tweeet).permit(:tweeet, :tweeet_image)
    end
end

app/helpers/tweeets_helper.rb
module TweeetsHelper
end

app/views/tweeets/_form.html.erb
<%= form_with(model: tweeet) do |form| %>
  <% if tweeet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweeet.errors.count, "error") %> prohibited this tweeet from being saved:</h2>

      <ul>
        <% tweeet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :tweeet %>
    <%= form.rich_text_area :tweeet, class: "form-control"%>
  </div>
   <div class="form-group">
      <%= form.file_field :tweeet_image, class: "form-control-file"%>
    </div>

  <div class="actions">
    <%= form.submit "Tweet", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweeets/edit.html.erb
<h1>Editing Tweeet</h1>

<%= render 'form', tweeet: @tweeet %>
<div class="mt-3">
  <%= link_to 'Show', @tweeet , class: "btn btn-primary"%> |
  <%= link_to 'Back', tweeets_path , class: "btn btn-dark"%>
</div>

app/views/tweeets/index.html.erb
<div class="row mt-4">
  <div class="col-md-5">
    <div class="card card-index mb-3 shadow">
      <div class="card-header">
          <h4>Profile</h4>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-4">
            <% if current_user.avatar.present? %>
              <div class="user-image-dash">
                <%= image_tag current_user.avatar %>
              </div>
            <% end %>
          </div>
          <div class="col-8">
            <strong><%= current_user.fullname %> </Strong><br>
            <small>@<%= current_user.username%></small>
          </div>
        </div><br><br>
        <%= link_to edit_user_registration_path do %>
          <%= fa_icon "pencil" ,class: "btn btn-warning"%> 
        <% end %>
      </div>
      <hr>
      <div class="ml-5 mr-5 mb-3">
        <div class="d-flex justify-content-between">
          <strong>Tweets</strong>
          <strong>Followers</strong>
          <strong>Following</strong>
        </div>
        <div class="d-flex justify-content-between">
          <span><%= current_user.tweeets.count%></span>
          <span><%= current_user.followers.count %></span>
          <span><%= current_user.followees.count %></span>
        </div>
      </div>
    </div>
    
  </div>
  <div class="col-md-7">
    <div class="card card-index shadow p-3">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="newtweet-tab" data-toggle="tab" href="#newtweet" role="tab" aria-controls="newtweet" aria-selected="false">New Tweet</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="tweets-tab" data-toggle="tab" href="#tweets" role="tab" aria-controls="tweets" aria-selected="false">Tweeets</a>
        </li> 
        <li class="nav-item">
          <a class="nav-link" id="followers-tab" data-toggle="tab" href="#followers" role="tab" aria-controls="followers" aria-selected="true">Followers</a>
        </li>
       <li class="nav-item">
          <a class="nav-link" id="following-tab" data-toggle="tab" href="#following" role="tab" aria-controls="following" aria-selected="false">Following</a>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="newtweet" role="tabpanel" aria-labelledby="newtweet-tab">
          <div class="p-3">
            <%= form_with(model: @tweeet) do |form| %>
              <div class="form-group">
                <%= form.rich_text_area :tweeet, class: "form-control", placeholder: "tweet about it"%>
              </div>
              <div class="form-group">
                <%= form.file_field :tweeet_image, class: "form-control-file"%>
              </div>
              <div class="form-group">
                <%= form.submit "Tweet", class: "btn btn-primary" %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="tab-pane fade" id="tweets" role="tabpanel" aria-labelledby="tweets-tab">
          <div class="scroll">
            <% @tweeets.each do |tweeet| %>
              <div class="mb-3">
                <div class="card p-4 mt-2 card-index-tweets">
                  <div class="row col-md-8">
                    <div class="col-3">
                      <% if tweeet.user.avatar.present? %>
                        <div class="user-image-tweeet">
                          <%= image_tag tweeet.user.avatar %>
                        </div>
                      <% end %>
                    </div>
                    <div class="col-9">
                      <strong><%= tweeet.user.fullname %></strong><br>
                      <small>@<%= tweeet.user.username %> - <span class="text-secondary mb-0"><%= time_ago_in_words(tweeet.created_at) %> ago</span></small><br>
                    </div>
                  </div><hr>
                  <div class="card-body">
                    <%= tweeet.tweeet %><br><br>
                    <% if tweeet.tweeet_image.present? %>
                      <div class="mb-3 tweeet-image">
                        <%= image_tag(tweeet.tweeet_image) %>
                      </div>
                    <% end %><br>
                    <%if @tweeet.user = current_user %>
                      <div class="d-flex justify-content-around mt-3">
                        <div>
                          <%= link_to tweeet_path(tweeet) do %>
                          <%= fa_icon "paragraph" ,class: "btn btn-primary"%>
                          <% end %>
                        </div>
                        <div>
                          <%= link_to edit_tweeet_path(tweeet) do %>
                          <%= fa_icon "pencil" ,class: "btn btn-warning"%>
                          <% end %>
                        </div>
                        <div>
                          <%= link_to tweeet_path(tweeet), method: :delete, data: { confirm: "Are you sure"} do %>
                          <%= fa_icon "trash" ,class: "btn btn-danger"%>
                          <% end %>
                        </div>
                      </div>
                    <%end %><hr>
                    <div class="d-flex justify-content-around">
                      <span>
                        <% if tweeet.liked?(current_user)%>
                          <%= link_to unlike_path(tweeet), method: :delete  do %> <%= fa_icon "heart" %><%end%>
                        <% else %>
                          <%= link_to like_path(tweeet), method: :put,class:"text-dark" do %> <%= fa_icon "heart" %><%end%>
                        <% end %>
                          &nbsp <%= tweeet.likes.count%></span>
                      <span><%= fa_icon "retweet" %> &nbsp 0</span>
                      <span>
                        <%= link_to tweeet_path(tweeet),class: "text-decoration-none" do%>
                          <%= fa_icon "comments" %>
                        <%end%> &nbsp <%= tweeet.comments.count%>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <div class="tab-pane fade" id="followers" role="tabpanel" aria-labelledby="followers-tab">
          <% current_user.followers.each do |follower| %>
            <ul class="list-group">
              <% if follower == current_user %> 
                <%= link_to  tweeets_path, class: "text-decoration-none text-dark" do %>
                  <li class="list-group-item"><%= follower.fullname%></li>                  
                <% end %>
              <% else %>
                <%= link_to user_path(follower), class: "text-decoration-none text-dark"  do  %>
                  <li class="list-group-item"><%= follower.fullname%></li>
                <% end %>
              <% end %>
            </ul>
          <% end %>
        </div>
        <div class="tab-pane fade" id="following" role="tabpanel" aria-labelledby="following-tab">
          <% current_user.followees.each do |follower| %>
            <ul class="list-group">
              <% if follower == current_user %> 
                <%= link_to  tweeets_path, class: "text-decoration-none text-dark" do %>
                  <li class="list-group-item"><%= follower.fullname%></li>                  
                <% end %>
              <% else %>
                <%= link_to user_path(follower), class: "text-decoration-none text-dark"  do  %>
                  <li class="list-group-item"><%= follower.fullname%></li>
                <% end %>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
    <div class="card card-trends shadow mb-3">   
      
    </div>
    <div class="p-1">
      
    </div>
  </div>
</div>

app/views/tweeets/new.html.erb
<h1>New Tweeet</h1>

<%= render 'form', tweeet: @tweeet %>

<%= link_to 'Back', tweeets_path %>

app/views/tweeets/show.html.erb
<div class="card mt-2 card-index-tweets">
  <div class="row col-md-5 mt-3">
    <div class="col-3">
      <% if @tweeet.user.avatar.present? %>
        <div class="user-image-tweeet">
          <%= image_tag @tweeet.user.avatar %>
        </div>
      <% end %>
    </div>
    <div class="col-9">
      <%= link_to  user_path(@tweeet.user.id), class: "text-decoration-none text-dark" do %>
        <strong><%= @tweeet.user.fullname %></strong><br>
      <% end %>
      <small>@<%= @tweeet.user.username %></small>
    </div>
  </div><hr>
  <div class="card-body">
    <%= @tweeet.tweeet %><br><br>
    <% if @tweeet.tweeet_image.present? %>
      <div class="mb-3 tweeet-image">
        <%= image_tag(@tweeet.tweeet_image) %>
      </div>
    <% end %><br>
    <small class="text-secondary text-right"><%= time_ago_in_words(@tweeet.created_at) %> ago</small><br><hr>
    <div class="d-flex justify-content-between px-2 mt-3">
      <span>
      <% if user_signed_in? %> 
        <% if @tweeet.liked?(current_user)%>
          <%= link_to unlike_path(@tweeet), method: :delete do %> <%= fa_icon "heart" %><%end%>
        <% else %>
          <%= link_to like_path(@tweeet), method: "put",class:"text-dark" do %> <%= fa_icon "heart" %><%end%>
        <% end %>
      <% end %>
        &nbsp&nbsp <%= @tweeet.likes.count%></span>
      <span><%= fa_icon "retweet" %> &nbsp&nbsp 0</span>
      <span>
                  <%= link_to tweeet_path(@tweeet),class: "text-decoration-none" do%>
                    <%= fa_icon "comments" %>
                  <%end%> &nbsp&nbsp <%= @tweeet.comments.count%>
                </span>
    </div>
  </div>
</div><br>
  <hr>
<div>
  <div class="card-body mb-5">
    <div class="row d-flex justify-content-center mb-5">
      <div class="col">
        <div class="headings d-flex justify-content-between align-items-center mb-3">
          <h3>Comments</h3>
        </div>
        <%= form_for([@tweeet,@comment]) do |f| %>
          <div class="form-group">
            <%= f.text_area :body, rows: 3, class: "form-control", placeholder: "Please enter a comment", autofocus: true %>
          </div>
          <div class="form-group">
            <%= f.submit class: "btn btn-primary btn-lg" %>
          </div>
        <% end %>
        <% @tweeet.comments.order(created_at: :desc).each do |comment| %>
          <% if comment.body.present? %>
            <div class="card p-3 mb-2 shadow">
              <div class="d-flex justify-content-between align-items-center">
                <div class="user d-flex flex-row align-items-center"> 
                  <% if comment.user.avatar.present? %>
                    <img src="<%= url_for(comment.user.avatar)%>" width="30" class="user-img rounded-circle mr-2">
                  <%end%>
                  <span><small> <%= link_to user_path(comment.user),class:"font-weight-bold text-primary" do %> <%= comment.user.fullname %><%end%></small></span> </div> <small> <%= time_ago_in_words(comment.created_at) %> ago</small>
                </div>
                <div class="action d-flex justify-content-between mt-2 align-items-center">
                    <small class="font-weight-bold px-4"> <%= comment.body %></small>
                  <div class="reply px-4 d-flex justify-content-between"> 
                    <span>
                      <% if current_user == comment.user %>
                        <%= link_to "delete", destroy_comment_path(@tweeet, comment_id: comment.id),method: :delete , class: "btn btn-danger btn-sm"%>
                      <% end %>
                    </span>
                  </div> 
                </div>
              </div>
           <% end %>
        <% end %>
        </div>
        
    </div>

</div>