config/routes.rb
Rails.application.routes.draw do
  
  get 'likes/create'
  get 'likes/destroy'
  root 'pages#index'
  get 'user/:id', to: 'pages#dashboard', as: 'user'
  get '/search', to: 'pages#search', as: 'search'
  post '/user/:id/follow', to: "follows#follow", as: "follow_user"
  post '/user/:id/unfollow', to: "follows#unfollow", as: "unfollow_user"
  get '/user/:id/followers', to: "follows#followers", as: "user_followers"
  devise_for :users
  delete 'tweeets/:tweeet_id/comment/:id', to: 'comments#destroy', as: "destroy_comment"
  put 'tweeets/:id/like', to: 'likes#create', as: "like"
  delete 'tweeets/:id/unlike', to: 'likes#destroy', as: "unlike"
  resources :tweeets do
    resources :comments
  end 
  resources :conversations do
    resources :messages
    delete '/read', to: "messages#read"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
  <%= link_to "Twitter", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
    </ul>
      
    <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <li class="nav-item">
          <%= link_to conversations_path, class: "nav-link" do  %>
           Messages 
            <% if notification.count > 0 %> 
              <span class="badge badge-success"><%= notification.count%> </span>
            <% end %>
          <% end %>
      </li>
      <li class="nav-item">
     
        <%= link_to "Dashboard", tweeets_path, class: "nav-link"  %>
      </li>
      <li class="nav-item">
        <%= link_to "New Tweet", tweeets_path, class: "btn btn-success mr-2"  %>
      </li> 
      <li class="nav-item">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-danger"  %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-dark"  %>
      </li>
      <li class="nav-item">
        <%= link_to "Log in", new_user_session_path, class: "btn btn-link"  %>
      </li>
      <% end %>
      
    </ul>
  </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
 <% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>">
    <div class="container">
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message %>
    </div>
  </div>
<% end %>

app/views/shared/_search.html.erb
<%= form_tag(search_path, method: 'get') do %>
  <div class="card-body row no-gutters align-items-center">
    <div class="col">
        <%= text_field_tag(:search, params[:search], class: "form-control form-control-lg form-control-borderless", type: "Search",placeholder:"Search User") %>
    </div>
        <%= submit_tag("Search", name: nil, class: "btn btn-primary btn-lg", type: "button") %>
  </div>
<% end %>