config/routes.rb
Rails.application.routes.draw do
  
  get 'likes/create'
  get 'likes/destroy'
  root 'pages#index'
  get 'user/:id', to: 'pages#dashboard', as: 'user'
  get '/search', to: 'pages#search', as: 'search'
  post '/user/:id/follow', to: "follows#follow", as: "follow_user"
  post '/user/:id/unfollow', to: "follows#unfollow", as: "unfollow_user"
  get '/user/:id/followers', to: "follows#followers", as: "user_followers"
  devise_for :users
  delete 'tweeets/:tweeet_id/comment/:id', to: 'comments#destroy', as: "destroy_comment"
  put 'tweeets/:id/like', to: 'likes#create', as: "like"
  delete 'tweeets/:id/unlike', to: 'likes#destroy', as: "unlike"
  resources :tweeets do
    resources :comments
  end 
  resources :conversations do
    resources :messages
    delete '/read', to: "messages#read"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/dashboard.html.erb
<div class="row mt-4">
  <div class="col-md-5">
    <div class="card card-index mb-3 shadow">
      <div class="card-header">
        <h4>Profile</h4>
      </div>
      <div class="card-body">
        <div class="d-flex justify-content-center">
          <div class="d-flex  flex-column">
            <% if @user.avatar.present? %>
              <div class="user-image-dash">
                <%= image_tag @user.avatar %>
              </div>
            <% end %><br>
            <strong><%= @user.fullname %> </Strong>
            <small>@<%= @user.username%></small>
          </div>
        </div><br><br>
        <% if user_signed_in?%>
          <% if current_user.followees.include?(@user) %>
            <div class="d-flex justify-content-between">
              <%= button_to "UnFollow", unfollow_user_path, method: "POST", class: "btn btn-danger" %>
              
              <%= button_to "Message", conversations_path(sender_id: current_user.id,recipient_id: @user.id), method: "POST" , class: "btn btn-primary" %>
            </div>
          <% else %>
            <%= button_to "Follow", follow_user_path, method: "POST" , class: "btn btn-primary" %>
          <% end %>
        <% else %>
          <%= button_to "Follow", follow_user_path, method: "POST" , class: "btn btn-primary" %>
        <% end %>
      </div><hr>
      <div class="ml-5 mr-5 mb-3">
        <div class="d-flex justify-content-between">
          <strong>Tweets</strong>
          <strong>Followers</strong>
          <strong>Following</strong>
        </div>
        <div class="d-flex justify-content-between">
          <span><%= @user.tweeets.count%></span>
          <span><%= @user.followers.count %></span>
          <span><%= @user.followees.count %></span>
        </div>
      </div> 
    </div> 
    
  </div>
  <div class="col-md-7">
    <div class="card card-index shadow p-3">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="tweeets-tab" data-toggle="tab" href="#tweeets" role="tab" aria-controls="tweeets" aria-selected="true">Tweets</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="followers-tab" data-toggle="tab" href="#followers" role="tab" aria-controls="followers" aria-selected="true">Followers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="following-tab" data-toggle="tab" href="#following" role="tab" aria-controls="following" aria-selected="false">Following</a>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="tweeets" role="tabpanel" aria-labelledby="tweeets-tab">
          <div class="scroll">
            <% @tweeets.each do |tweeet| %>
              <div class="mb-2">
                <div class="card p-3 mt-2 card-index-tweets">
                  <div class="row col-md-8">
                    <div class="col-4">
                      <% if tweeet.user.avatar.present? %>
                        <div class="user-image-tweeet">
                          <%= image_tag tweeet.user.avatar %>
                        </div>
                      <% end %>
                    </div>
                    <div class="col-8">
                      <strong><%= tweeet.user.fullname %></strong><br>
                      <small>@<%= tweeet.user.username %> - <span class="text-secondary mb-0"><%= time_ago_in_words(tweeet.created_at) %> ago</span></small>
                    </div>
                  </div><hr>
                  <div class="card-body">
                    <%= link_to tweeet_path(tweeet), class: "text-decoration-none text-dark" do %>
                      <%= tweeet.tweeet %><br><br>
                      <% if tweeet.tweeet_image.present? %>
                        <div class="mb-3 tweeet-image">
                          <%= image_tag(tweeet.tweeet_image) %>
                        </div>
                      <% end %><br><hr>
                    <% end %>
                    <div class="d-flex justify-content-between px-2">
                      <span>
                        <% if user_signed_in? %> 
                          <% if tweeet.liked?(current_user)%>
                            <%= link_to unlike_path(tweeet), method: :delete  do %> <%= fa_icon "heart" %><%end%>
                          <% else %>
                            <%= link_to like_path(tweeet), method: :put,class:"text-dark" do %> <%= fa_icon "heart" %><%end%>
                          <% end %>
                        <% end %>
                        &nbsp&nbsp <%= tweeet.likes.count%>
                      </span>
                      <span><%= fa_icon "retweet" %> &nbsp&nbsp 0</span>
                      <span>
                        <%= link_to tweeet_path(tweeet),class: "text-decoration-none" do%>
                          <%= fa_icon "comments" %>
                        <% end %> &nbsp&nbsp <%= tweeet.comments.count%>
                      </span>
                    </div>
                  </div> 
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <div class="tab-pane fade" id="followers" role="tabpanel" aria-labelledby="followers-tab">
          <% @user.followers.each do |follower| %>
            <ul class="list-group">
              <% if follower == current_user %> 
                <%= link_to  tweeets_path, class: "text-decoration-none text-dark" do %>
                  <li class="list-group-item"><%= follower.fullname%></li>                  
                <% end %>
              <% else %>
                <%= link_to user_path(follower), class: "text-decoration-none text-dark"  do  %>
                  <li class="list-group-item"><%= follower.fullname%></li>
                <% end %>
              <% end %>
            </ul>
          <% end %>
        </div>
        <div class="tab-pane fade" id="following" role="tabpanel" aria-labelledby="following-tab">
          <% @user.followees.each do |follower| %>
            <ul class="list-group">
              <% if follower == current_user %> 
                <%= link_to  tweeets_path, class: "text-decoration-none text-dark" do %>
                  <li class="list-group-item"><%= follower.fullname%></li>                  
                <% end %>
              <% else %>
                <%= link_to user_path(follower), class: "text-decoration-none text-dark"  do  %>
                  <li class="list-group-item"><%= follower.fullname%></li>
                <% end %>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/pages/index.html.erb
<div class="row mt-5">
  <div class="col-md-9">
    <div class="scroll">
      <% @tweeets.each do |tweeet| %>
        <div class="mb-4">
          <div class="card p-4 card-index-tweets">
            <div class="row col-md-5">
              <div class="col-4">
                <% if tweeet.user.avatar.present? %>
                  <div class="user-image-tweeet">
                    <%= image_tag tweeet.user.avatar %>
                  </div>
                <% end %>
              </div>
              <div class="col-8">
                <% if user_signed_in?%>
                  <% if tweeet.user == current_user %> 
                    <%= link_to  tweeets_path, class: "text-decoration-none text-dark" do %>
                      <strong><%= tweeet.user.fullname %></strong><br>
                    <% end  %>
                  <% else %>
                    <%= link_to  user_path(tweeet.user.id), class: "text-decoration-none text-dark" do %>
                      <strong><%= tweeet.user.fullname %></strong><br>
                    <% end  %>
                  <% end %> 
                <% else %>
                  <%= link_to  user_path(tweeet.user.id), class: "text-decoration-none text-dark" do %>
                    <strong><%= tweeet.user.fullname %></strong><br>
                  <% end  %> 
                <% end %> 
                <small>@<%= tweeet.user.username %> - <span class="text-secondary mb-0"><%= time_ago_in_words(tweeet.created_at) %> ago</span></small><br>
              </div>
            </div><hr>
            <%= link_to tweeet_path(tweeet), class: "text-decoration-none text-dark" do %>
              <div class="card-body">
                <%= tweeet.tweeet %><br><br>
                <% if tweeet.tweeet_image.present? %>
                  <div class="mb-3 tweeet-image">
                    <%= image_tag(tweeet.tweeet_image) %>
                  </div>
                <% end %>
              </div><hr>
            <% end %>
              <div class="d-flex justify-content-around">
                <span>
                  <% if user_signed_in? %> 
                    <% if tweeet.liked?(current_user)%>
                      <%= link_to unlike_path(tweeet), method: :delete  do %> <%= fa_icon "heart" %><%end%>
                    <% else %>
                      <%= link_to like_path(tweeet), method: :put,class:"text-dark" do %> <%= fa_icon "heart" %><%end%>
                    <% end %>
                  <% else %>
                    <%= link_to like_path(tweeet), method: :put,class:"text-dark" do %> <%= fa_icon "heart" %><%end%>                  
                  <% end %>
                    &nbsp&nbsp <%= tweeet.likes.count%></span>
                <span><%= fa_icon "retweet" %> &nbsp&nbsp 0</span>
                <span>
                  <%= link_to tweeet_path(tweeet),class: "text-decoration-none" do%>
                    <%= fa_icon "comments" %>
                  <%end%> &nbsp&nbsp <%= tweeet.comments.count%>
                </span>
              </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-3">
    <div class="card card-index mb-3 shadow">
      <div class="card-header">
        <h4>Who to follow</h4>
      </div>
      <div class="card-body">
      <% @user.each do |user| %>
      <%= link_to  user_path(user.id), class: "text-decoration-none text-dark" do %>
        <div class="card card-user mb-3 p-2">
          <div class="row">
            <div class="col-2">
              <% if user.avatar.present? %>
                <div class="user-image">
                  <%= image_tag user.avatar %>
                </div>
              <% end %>
            </div>
            <div class="col-10">
              <strong><%= user.fullname  %></strong><br>
              <small class="text-secondary mt-0">@<%= user.username  %></small>
            </div>
          </div>
        </div>
      <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/search.html.erb
  <% @friends.each do |user| %>
    <%= link_to  user_path(user.id), class: "text-decoration-none text-dark" do %>
    <div class="card card-index-tweets mb-3">
      <div class="row">
        <div class="col-4">
          <% if user.avatar.present? %>
            <div class="card-body search-user-image">
                <%= image_tag user.avatar %>
            </div>
          <% end %>
        </div>
        <div class="col-8">
          <div class="card-body">
            <div class="card-title"><h3><%= user.fullname %></h3></div>
            <p>@<%= user.username %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>